---
stages: [build, deploy]

variables:
  AWS_REGION: "us-east-1"
  PROJECT_NAME: "ecs-cicd-project"
  APP_DIR: "app"
  TF_DIR: "terraform"
  IMAGE_TAG: "${CI_COMMIT_SHORT_SHA}"
  SERVICE_SIZE: "small"
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: "overlay2"

build:
  stage: build
  image: docker:25
  services:
    - name: docker:25-dind
      alias: docker
  script:
    - >
      aws ecr get-login-password --region "$AWS_REGION"
      | docker login --username AWS --password-stdin
      "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    - export ECR_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}"
    - docker build -t "${ECR_URL}:${IMAGE_TAG}" -t "${ECR_URL}:latest" "${APP_DIR}"
    - docker push "${ECR_URL}:${IMAGE_TAG}"
    - docker push "${ECR_URL}:latest"
  only: [main]

deploy:
  stage: deploy
  image: hashicorp/terraform:1.8
  script:
    - cd "${TF_DIR}"
    - terraform init -input=false
    - >
      terraform apply -auto-approve
      -var="project_name=${PROJECT_NAME}"
      -var="region=${AWS_REGION}"
      -var="ecr_repo_url=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}"
      -var="image_tag=${IMAGE_TAG}"
      -var="service_size=${SERVICE_SIZE}"
  only: [main]
